# Header
language: r
sudo: false
cache: packages
r: devel

#env
env:
  global:
  - MAKEFLAGS="-j 2"

# Custom parts:

#install
install:
- R -e 'if (!requireNamespace("dplyr", quietly = TRUE)) install.packages("dplyr")'

#script
script:
- R -e 'library(dplyr); sessionInfo()'
- R -e 'install.packages("https://github.com/RcppCore/drat/raw/gh-pages/src/contrib/Rcpp_0.12.8.2.tar.gz", repos = NULL)'
- R -e 'library(dplyr); sessionInfo()'

